import {
  Eye,
  Blocks,
  ArrowUpFromLine,
  ArrowDownToLine,
  Loader2,
  Plus,
  Settings,
  Trash,
  ScrollText,
  Slash,
  ListPlus,
  CircleCheckBig,
  OctagonPause,
  CircleX,
  AlignJustify,
  LayoutGrid,
  ChevronDown,
  Braces,
} from 'lucide-react'

export const Icons = {
  eye: Eye,
  logo: Blocks,
  spinner: Loader2,
  plus: Plus,
  push: ArrowUpFromLine,
  pull: ArrowDownToLine,
  settings: Settings,
  script: ScrollText,
  trash: Trash,
  slash: Slash,
  queued: ListPlus,
  completed: CircleCheckBig,
  stopped: OctagonPause,
  failed: CircleX,
  grid: LayoutGrid,
  list: AlignJustify,
  more: ChevronDown,
  json: Braces,
}
